# Generated by Django 4.1.7 on 2023-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('prenom', models.CharField(max_length=100, unique=True)),
                ('niveau', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
