# Generated by Django 4.1.7 on 2023-05-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudo',
        ),
    ]
