# Generated by Django 4.1.7 on 2023-05-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
    ]
