# Generated by Django 4.1.7 on 2023-04-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='DateDebut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='DateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cin',
            field=models.CharField(max_length=100),
        ),
    ]
