# Generated by Django 4.1.7 on 2023-04-24 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reservation_datedebut_reservation_datefin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunteur', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('DateDebut', models.DateField(default=datetime.datetime.now)),
                ('DateFin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='cin',
            new_name='reservateur',
        ),
    ]
