# Generated by Django 4.1.7 on 2023-04-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password'),
        ('books', '0004_emprunt_rename_cin_reservation_reservateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nom',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='nomLivre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.livre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nomLivre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.livre'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
