# Generated by Django 4.1.7 on 2023-04-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password'),
        ('books', '0005_remove_emprunt_nom_remove_reservation_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLivre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.livre')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
