# Generated by Django 4.1.7 on 2023-04-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='contenu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
