# Generated by Django 4.1.7 on 2023-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_livre_description_livre_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.CharField(default=12, max_length=5000),
            preserve_default=False,
        ),
    ]
