# Generated by Django 4.1.7 on 2023-05-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_delete_user'),
        ('books', '0010_alter_commentaire_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
